name: Auto publish

on:
  push:
    paths:
      - 'info.json' # Triggers only if the mod info file is updated
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish mod
        uses: Penguin-Spy/factorio-mod-portal-publish@main
        with:
          factorio-api-key: ${{ secrets.FACTORIO_MOD_API_KEY }}
